//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOfTweets.Common.Api.Twitter.Responses
{

    public class ResponseRetweetClass
    {

        public Coordinates geo { get; set; }

        public ResponseTweet retweeted_status { get; set; }

        public bool? truncated { get; set; }

        public string id_str { get; set; }

        public string coordinates { get; set; }

        public UserClass user { get; set; }

        public string retweet_count { get; set; }

        public long? in_reply_to_status_id { get; set; }

        public string text { get; set; }

        public bool? favorited { get; set; }

        public string created_at { get; set; }

        public string in_reply_to_status_id_str { get; set; }

        public string in_reply_to_screen_name { get; set; }

        public string source { get; set; }

        public string in_reply_to_user_id_str { get; set; }

        public Place place { get; set; }

        public long? in_reply_to_user_id { get; set; }

        public long id { get; set; }

        public string contributors { get; set; }

        public bool? retweeted { get; set; }
    }


}