//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldOfTweets.Common.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FieldOfTweets.Common.UI.Resources.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved to favourites.
        /// </summary>
        public static string addfavourite {
            get {
                return ResourceManager.GetString("addfavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customise.
        /// </summary>
        public static string customise {
            get {
                return ResourceManager.GetString("customise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customise home screen.
        /// </summary>
        public static string customisehomescreen {
            get {
                return ResourceManager.GetString("customisehomescreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favourite.
        /// </summary>
        public static string favourite {
            get {
                return ResourceManager.GetString("favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favourites.
        /// </summary>
        public static string favourites {
            get {
                return ResourceManager.GetString("favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites List.
        /// </summary>
        public static string favouriteslist {
            get {
                return ResourceManager.GetString("favouriteslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your favourite tracks.
        /// </summary>
        public static string favouritetracks {
            get {
                return ResourceManager.GetString("favouritetracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fetching more favourites.
        /// </summary>
        public static string fetchingmorefavourites {
            get {
                return ResourceManager.GetString("fetchingmorefavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To take full advantage of Mehdoh you must authorise the application to access your Twitter account..
        /// </summary>
        public static string pleaseauthorise {
            get {
                return ResourceManager.GetString("pleaseauthorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refreshing favourites.
        /// </summary>
        public static string refreshingfavourites {
            get {
                return ResourceManager.GetString("refreshingfavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed from favourites.
        /// </summary>
        public static string removefavourite {
            get {
                return ResourceManager.GetString("removefavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removing favourite.
        /// </summary>
        public static string removingfavourite {
            get {
                return ResourceManager.GetString("removingfavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saving favourite.
        /// </summary>
        public static string savingfavourite {
            get {
                return ResourceManager.GetString("savingfavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unfavourite.
        /// </summary>
        public static string unfavourite {
            get {
                return ResourceManager.GetString("unfavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your favourites.
        /// </summary>
        public static string yourfavourites {
            get {
                return ResourceManager.GetString("yourfavourites", resourceCulture);
            }
        }
    }
}
